os: linux

sudo: enabled

git:
  submodules: true

language: python

matrix:
  include:
  - name: "host_python_27"
    python: "2.7"
  - name: "host_python_35"
    python: "3.5"
  - name: "host_python_3.6"
    python: "3.6"
  - name: "host_python_37_dev"
    python: "3.7-dev"

before_install:
  - sudo apt-get install g++
  - sudo apt-get install cmake
  - sudo apt-get install bison
  - sudo apt-get install flex
  - sudo apt-get install ninja-build
  - sudo apt-get install python3.5-dev
  # We need to install python-3.6 from a third party repo as it is not
  # available as a standard package on Travis Trusty VMs.
  - sudo add-apt-repository ppa:jonathonf/python-3.6 -y
  - sudo add-apt-repository ppa:jonathonf/python-3.7 -y
  - sudo apt-get update -q
  - sudo apt-get install python3.6
  - sudo apt-get install python3.6-dev
  - sudo apt-get install python3.7
  - sudo apt-get install python3.7-dev

install:
  - pip install pyyaml
  - pip install six
  - pip install pytype

# Before testing the code, "compile" it by statically analyzing the types.
# TODO(rechen): Support specifying the pytype inputs in setup.cfg instead.
# Due to https://github.com/travis-ci/travis-ci/issues/1066, if we want
# the build to stop on pytype failure, we have to use one large command.
# We pass the -f option to run_tests so that the script aborts at the first
# failure and gives a less cluttered output.
script: |
  pytype\
    pytype/compat.py pytype/debug.py pytype/utils.py pytype/pyc\
    --exclude pytype/pyc/*_test.py &&
  python build_scripts/run_tests.py -f

notifications:
  email:
    recipients:
      - pytype@googlegroups.com
    on_success: change
    on_failure: always
